### ISSUE TITLE
cannot find data by your link mentioned in `docs/training.md`

### ISSUE THREAD

**Issue by itaowei** [graykode/commit-autosuggestions#4]
As mentioned in this [doc](https://github.com/graykode/commit-autosuggestions/blob/master/docs/training.md), 
`The data we used was put on a [google drive](https://drive.google.com/drive/folders/1_8lQmzTH95Nc-4MKd1RP3x4BVc8tBA6W?usp=sharing)`. However, I cannot find any data in that URL. Could you help me check that URL?

**Comment by graykode** [comment]
@itaowei Hello Thanks for your issue.

The training data used when creating commit-autosuggestions for the first time is different from the data used when experimenting.

https://github.com/graykode/commit-autosuggestions/tree/master/experiment/dataset <- just use this data!!
